// ...
public class ConfigManager {
    // ...
    public double THIEN_DINH_BONUS;
    public int THIEN_DINH_LINH_KHI_CONG_THEM; // <-- THÊM BIẾN MỚI

    // ...
    public void loadConfig() {
        // ...
        THIEN_DINH_BONUS = config.getDouble("thien-dinh.he-so-bonus", 3.0);
        THIEN_DINH_LINH_KHI_CONG_THEM = config.getInt("thien-dinh.linh-khi-cong-them-moi-giay", 3); // <-- THÊM DÒNG NÀY
        // ...
    }
    // ...
}
